version: "3.1"

services:
  jenkins:
    build:
      context: ../jenkins
      dockerfile: Dockerfile
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    name: jenkinsVolume