version: "3.1"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - jenkinsVolume:/var/jenkins_home

volumes:
  jenkinsVolume:
    name: jenkinsVolume